### ISSUE TITLE
Possible FastSLAM bug in the correction step - importance weight

### ISSUE THREAD

**Issue by rayryeng** [conorhennessy/SLAM-Course-Solutions#3]
Hi!  Thanks for posting these solutions.  Absolutely fantastic to see these alongside the course.  I have a question with regards to the importance weight for a particle in FastSLAM.  Specifically in your `correction_step.m` file:

```
% TODO: compute the likelihood of this observation, multiply with the former weight
%       to account for observing several features in one time step
% Weight, this corresponds to line 13 of slide 44 of FAST SLAM lecture (12)
particles(i).weight = 1/sqrt(det(2 * pi * Q)) * exp(-0.5 * (Z_diff)' * inv(Q) * Z_diff);
```

The note specifically mentions multiplying with the former weight.  You are not doing that here.  I believe this should be:

```
particles(i).weight = particles(i).weight * 1/sqrt(det(2 * pi * Q)) * exp(-0.5 * (Z_diff)' * inv(Q) * Z_diff);
```

If not, can you explain why this is not so?  As a reference, @kiran-mohan's reference implementation does do this: https://github.com/kiran-mohan/SLAM-Algorithms-Octave/blob/master/6_FastSLAM/octave/correction_step.m#L73

Thanks!

**Comment by conorhennessy** [comment]
I am glad that you have found my solutions helpful @rayryeng! I am very glad 😃 

While my SLAM & VPR knowledge is well and truly rusty, you are correct - I should have been multiplying the former weight in the last step of `s8_fast_slam` [here](https://github.com/conorhennessy/SLAM-Course-Solutions/blob/master/s8_fast_slam/octave/correction_step.m#L81). I have now resolved this with PR #4.

Thanks for linking @kiran-mohan's solution to the same exercise, they do indeed multiply by the former weight in this last step. A very handy link there to check if this change was right, thank you again.

If you notice anything else or wish to make any other changes, do feel free to raise a PR against this repo.

**Comment by rayryeng** [comment]
Thanks @conorhennessy! All the best and stay safe!

**Comment by conorhennessy** [comment]
No worries, more so, thank you! My apologies for taking so long to get back to you too.

I am very glad you posted this issue.

You too, all the best :)

**Comment by rayryeng** [comment]
Ah no worries! Thanks for fixing it regardless! ~You also may need to update the visualizations on the main repo page / README for FastSLAM due to the importance weights changing. I think I can do this in a couple of days and can submit a PR with a new updated GIF.~

Oops. You've done this! I needed to examine the PR properly. Thanks again! This is awesome!

**Comment by conorhennessy** [comment]
Ayy good to double-check, no worries.

I'm glad this is being enjoyed by others :)
